---
title: 'FIM Update'
author: ' Manu and Georgia '
date: "`r glue::glue(format(Sys.Date(), '%A, %B %d %Y'), ' at ', format(Sys.time(), '%I:%M %p'))`"
tz: 'America/New_York'
mainfont: Serif
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: false
    theme: cerulean
    highlight: zenburn
    highretina: 3
    self_contained: yes
    css: [style.css]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE,
  fig.align = 'center',
  warning = FALSE,
  message = FALSE,
  cache = FALSE,
  results='hide',
  fig.keep='all'
)
```

```{r}
librarian::shelf(ggplot2, gt, readr)
  plots <- read_rds("C:\\Users\\GNabors\\OneDrive - The Brookings Institution\\Documents\\FIM\\07-2024\\beta\\data\\plots")
```

# Fiscal Impact Measure
```{r fiscal_impact}
plots$fiscal_impact 
```

# Summary 
```{r, include=TRUE, results = 'show'}
summary_tbl
```

# FIM Consistent Purchases
````{r purchases_contribution}
plots$state_contribution
plots$federal_contribution
````

# Grants
```{r grants_contribution}
plots$consumption_grants_contribution
plots$investment_grants_contribution
```



# Taxes

## Corporate Taxes 

```{r corp_contribution}
plots$federal_corporate_taxes_contribution
plots$state_corporate_taxes_contribution
```

## Non-Corporate Taxes {.tabset .tabset-pills}
```{r non_corp_contribution}
plots$federal_non_corporate_taxes_contribution
plots$state_non_corporate_taxes_contribution
```

# Transfers 

## Total
```{r transfers_contribution}
plots$transfers_contribution
```

## Health Outlays 
```{r health_outlays_contribution}
plots$federal_health_outlays_contribution
plots$state_health_outlays_contribution
```

## Subsidies (non-ARP)
```{r non_arp_subsidies_contribution}
plots$state_subsidies_contribution
plots$federal_subsidies_contribution
```

## Subsidies (ARP)
```{r arp_subsidies_contribution}
plots$federal_aid_to_small_businesses_arp_contribution
```

## Unemployment Insurance
```{r ui_contribution}
plots$federal_ui_contribution
plots$state_ui_contribution
```

## Other aid to vulernable households 
```{r other_aid_vulnerable_households_contribution}
plots$federal_other_vulnerable_arp_contribution
```

## Rebate Checks 
```{r rebate_checks_contribution}
plots$rebate_checks_contribution
```

## Rebate Checks (ARP)
```{r rebate_checks_arp_contribution}
plots$rebate_checks_arp
```

## Direct aid to households 
```{r direct_aid_households_contribution}
plots$federal_other_direct_aid_arp_contribution
```

## Social Benefits Remainder
``` {r social_benefits_contribution}
plots$federal_social_benefits_contribution
plots$state_social_benefits_contribution 
```