---
title: 'FIM Update'
author: ' Manu, Georgia, and Sarah '
date: "`r glue::glue(format(Sys.Date(), '%A, %B %d %Y'), ' at ', format(Sys.time(), '%I:%M %p'))`"
tz: 'America/New_York'
mainfont: Serif
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: false
    theme: cerulean
    highlight: zenburn
    highretina: 3
    self_contained: yes
    css: [style.css]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE,
  fig.align = 'center',
  warning = FALSE,
  message = FALSE,
  cache = FALSE,
  results='hide',
  fig.keep='all',
  fig.width = 7,   
  fig.height = 5,   
  out.width = "80%",
  dpi = 300         
)
```

```{r}
librarian::shelf(ggplot2, gt, readr)
  plots <- read_rds('data/plots')
```



# Fiscal Impact Measure
```{r fiscal_impact}
plots$fiscal_impact_measure
```



# Summary 
```{r, include=TRUE, results = 'show'}
summary_tbl
```


# FIM Contribution
````{r fim_contribution}
plots$federal_contribution
plots$state_contribution
plots$consumption_contribution

````

# FIM Consistent Components
````{r fim_component_real}
plots$fim_federal_purchases_real
plots$fim_state_purchases_real
plots$consumption_real

````

# NIPA Consistent Components
````{r nipa_component_real}
plots$nipa_federal_purchases_real
plots$nipa_state_purchases_real

````

