
# levels.R

# Load packages - purr is not used in fiscal_impact_BETA.R
packages <- c(
  "tidyverse", "tsibble", "lubridate", "glue", 
  "TimTeaFan/dplyover", "zoo", "TTR", "fs", "gt", "purr",
  "openxlsx", "snakecase", "rlang", "BrookingsInstitution/ggbrookings"
)

librarian::shelf(packages)

# The FIM calculates the effect of fiscal policy on the growth rate of GDP. This code examines the impact of 
# fiscal policy on GDP level. It relies on inputs that are generated by fiscal_impact_BETA, so run that script first to ensure
# you have the necessary objects saved in memory. 

###################
# DEFINE QUARTERS #
###################

# Define and set start and end quarter. The start_quarter and end_quarter
# variables can be modified to determine cumulative contributions of the FIM 
# from any two quarters. 
start_quarter <- yearquarter("2020 Q1")
start_position <- which(usna$date == start_quarter)
end_quarter <- yearquarter("2026 Q2")
end_position <- which(usna$date == end_quarter) 
base_quarter <- start_quarter - 1 
base_position <- which(usna$date == base_quarter) 

######################################
# DEFINE CUMULATIVE PRODUCT FUNCTION #
######################################

# Generate "cumprod_growth" function. This function takes a deflator data series 
# as its input. It calculates the cumulative product of (1+rpgg+dg) beginning in 
# the start_quarter using rpgg from real_potential_gdp_growth_test. 
cumprod_growth <- 
  function(deflator){
    data.frame(real_potential_gdp_growth_test, deflator) %>% 
      mutate(
        sum = ifelse(date >= start_quarter, data_series.1 + data_series, 0), # sum the growth rates beginning in start_quarter, otherwise 0 
        cumprod = ifelse(date >= start_quarter, cumprod(1 + sum) - 1, NA) # get the cumulative product of the summed growth rates starting in start_quarter 
      ) %>%
      select(
        cumprod # keep only the cumulative product 
      )
  }

# Calculate the cumulative product of the growth rates for each of the deflators.

# Consumption Deflator 
cumprod_growth_consumption <- cumprod_growth(consumption_deflator_growth_test)

# Federal Purchases Deflator 
cumprod_growth_federal_purchases <- cumprod_growth(federal_purchases_deflator_growth_test)

# Consumption Grants Deflator 
cumprod_growth_consumption_grants <- cumprod_growth(consumption_grants_deflator_growth_test)

# Investment Grants Deflator 
cumprod_growth_investment_grants <- cumprod_growth(investment_grants_deflator_growth_test)

# State Purchases Deflator 
cumprod_growth_state_purchases <- cumprod_growth(state_purchases_deflator_growth_test)


#################################
# GENERATE REAL GDP PROJECTIONS #
#################################

# The FIM minus neutral calculation is in real terms. Our counterfactual GDP, therefore, must be calculated in real terms. We'll need to use real GDP. 
# We pull in real GDP from Haver, but we need to generate projections of real GDP for our forecast period. 
# To do this, we'll use CBO growth rates for real GDP. 

# Import the raw CBO and Haver National Accounts Data
projections <- import_projections()
national_accounts <- import_national_accounts()

# Define create_real_gdp_function
create_real_gdp <- function(
    national_accounts, 
    projections, 
    placeholder_nas
) {
  projections1 <- projections %>% 
    mutate(real_gdp_growth = q_g(gdph)) %>% # gdph is the haver code for real gdp 
    select(date, real_gdp_growth) %>%
    # Filter to select only the growth rates from future quarters
    filter(date > current_quarter)
  
  # Select columns of interest from the national accounts tibble
  national_accounts1 <- national_accounts %>% 
    # Haver code for real GDP is 'gdph'
    select(date, gdph) %>% 
    rename(real_gdp = gdph)
  # Define an index number for the current data point and end data point
  current_index <- which(national_accounts1$date == current_quarter)
  seed_real_gdph = national_accounts1$real_gdp[current_index]
  
  # Define new real GDP projections by growing current real GDP (seed) at CBO growth rates
  # using the cumulative_series() function
  new_real_gdp_projections <- cumulative_series(
    seed = seed_real_gdph,
    growth_rates = 1 + projections1$real_gdp_growth
  )
  
  # Define projections row as this adjusted forecast
  projections2 <- projections1 %>%
    mutate(real_gdp = new_real_gdp_projections) %>%
    select(date, real_gdp)
  
  # Merge the national accounts with the projection using the commonly named `gdp`
  # and `date` columns. 
  result <- coalesce_join(national_accounts1, projections2, by = 'date') %>%
    # Rename the gdp column to generic data_series
    rename(data_series = real_gdp) %>%
    # Merge with a data frame of NAs extending to 2034 Q3
    coalesce_join(., placeholder_nas, by = "date") %>%
    # Repopulate the NAs to be 0s
    mutate(across(everything(), ~ replace_na(., 0))) %>%
    # Pull just the data_series 
    pull(data_series)
  
  return(result)
}

# Define real_gdp series 
real_gdp <- create_real_gdp(
  national_accounts,
  projections,
  create_placeholder_nas()
)

######################
# GENERATE DEFLATORS #
######################

# Read in data sources to be combined
national_accounts <- import_national_accounts()
projections <- import_projections()

create_federal_purchases_deflator <- function(
    national_accounts, 
    projections
) {
  # Select column of interest from the projections tibble
  projections <- projections %>% 
    # Divide federal purchases "gf" by real federal purchases "gfh".
    mutate(data_series = gf / gfh) %>%
    select(date, data_series)
  
  # Select columns of interest from the national accounts tibble
  national_accounts <- national_accounts %>% 
    # Divide federal purchases "gf" by real federal purchases "gfh".
    mutate(data_series = gf / gfh) %>%
    select(date, data_series)
  
  # Merge the national accounts with the projection using the commonly named `data_series`
  # and `date` columns. The historic (national accounts) data take precedence in
  # the case of any conflicting observations.
  result <- coalesce_join(national_accounts, projections, by = 'date') %>%
    # Repopulate the NAs to be 0s
    mutate(across(everything(), ~ replace_na(., 0))) %>%
    # Pull just the data_series 
    pull(data_series)
  
  return(result)
}

create_state_purchases_deflator <- function(
    national_accounts, 
    projections
) {
  # Select column of interest from the projections tibble
  projections <- projections %>% 
    # Divide state purchases "gs" by real state purchases "gsh".
    mutate(data_series = gs / gsh) %>%
    select(date, data_series)
  
  # Select columns of interest from the national accounts tibble
  national_accounts <- national_accounts %>% 
    # Divide state purchases "gs" by real state purchases "gsh".
    mutate(data_series = gs / gsh) %>%
    select(date, data_series)
  
  # Merge the national accounts with the projection using the commonly named `data_series`
  # and `date` columns. The historic (national accounts) data take precedence in
  # the case of any conflicting observations.
  result <- coalesce_join(national_accounts, projections, by = 'date') %>%
    # Repopulate the NAs to be 0s
    mutate(across(everything(), ~ replace_na(., 0))) %>%
    # Pull just the data_series 
    pull(data_series)
  
  return(result)
}

create_consumption_deflator <- function(
    national_accounts, 
    projections
) {
  # Select column of interest from the projections tibble
  projections <- projections %>% 
    # Divide consumption "c" by real consumption "ch".
    mutate(data_series = c / ch) %>%
    select(date, data_series)
  
  # Select columns of interest from the national accounts tibble
  national_accounts <- national_accounts %>% 
    # Divide consumption "c" by real consumption "ch".
    mutate(data_series = c / ch) %>%
    select(date, data_series)
  
  # Merge the national accounts with the projection using the commonly named `data_series`
  # and `date` columns. The historic (national accounts) data take precedence in
  # the case of any conflicting observations.
  result <- coalesce_join(national_accounts, projections, by = 'date') %>%
    # Repopulate the NAs to be 0s
    mutate(across(everything(), ~ replace_na(., 0))) %>%
    # Pull just the data_series 
    pull(data_series)
  
  return(result)
}

# Generate the deflators for each of the contributions

# Federal Purchases Deflator 
federal_purchases_deflator <- create_federal_purchases_deflator(national_accounts,
                                                                projections)

# State Purchases Deflator
state_purchases_deflator <- create_state_purchases_deflator(national_accounts,
                                                            projections)

# Consumption Deflator 
consumption_deflator <- create_consumption_deflator(national_accounts,
                                                    projections)


#################################
# DEFINE CONTRIBUTION FUNCTIONS #
#################################

# Define Minus Neutral Function 
counterfactual_levels <- function(x, #the data in question 
                                  cumprod #cumulative product of deflator and real potential gdp growth 
                                  #calculated from cumprod function defined in previous function 
) {
  output <- x- x[base_position] * (cumprod+1)
  return(output)
}

# Define MPC Function
mpc_levels <- function(x, mpc_matrix) {
  if (nrow(mpc_matrix) != length(x)) {
    stop("The number of rows in the mpc_matrix must equal the length of the series.")
  }
  vert_x <- matrix(x, ncol = 1)
  vert_x[is.na(vert_x)] <- 0
  output <- mpc_matrix %*% vert_x
  return(output)
}

# Define Wrapper Function 
contribution_levels <- function(x, mpc_matrix = NULL, cumprod) {
  # Apply MPC Function
  if (!is.null(mpc_matrix)) {
    x <- x %>%
      mpc_levels(x = ., mpc_matrix = mpc_matrix)
  }
  
  # Apply the minus_neutral function to x
  result <- x %>%
    counterfactual_levels(x = ., cumprod = cumprod)
}

################################
# GET CONTRIBUTIONS AND LEVELS #
################################

# Federal Purchases 
federal_purchases_contribution_levels <- contribution_levels(
  x = federal_purchases_test$data_series, 
  mpc_matrix = NULL,
  cumprod = cumprod_growth_federal_purchases$cumprod
)

# Consumption Grants
consumption_grants_contribution_levels <- contribution_levels(
  x = consumption_grants_test$data_series,
  mpc_matrix = NULL,
  cumprod = cumprod_growth_consumption_grants$cumprod
)

# Investment Grants 
investment_grants_contribution_levels <- contribution_levels(
  x = investment_grants_test$data_series, 
  mpc_matrix = NULL,
  cumprod = cumprod_growth_investment_grants$cumprod
)

# State Purchases
state_purchases_contribution_levels <- contribution_levels(
  x = state_purchases_test$data_series, 
  mpc_matrix = NULL,
  cumprod = cumprod_growth_state_purchases$cumprod
)

# Federal Non Corporate Taxes
federal_non_corporate_taxes_contribution_levels <- contribution_levels(
  x = federal_non_corporate_taxes_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_non_corporate_taxes.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# State Non Corporate Taxes
state_non_corporate_taxes_contribution_levels <- contribution_levels(
  x = state_non_corporate_taxes_test$data_series,  
  mpc_matrix = readRDS("cache/mpc_matrices/state_non_corporate_taxes.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Corporate Taxes
federal_corporate_taxes_contribution_levels <- contribution_levels(
  x = federal_corporate_taxes_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_corporate_taxes.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Supply Side IRA 
supply_side_ira_contribution_levels <- contribution_levels(
  x = supply_side_ira_test$data_series, 
  mpc_matrix = NULL,
  cumprod = cumprod_growth_consumption$cumprod
)

# State Corporate Taxes
state_corporate_taxes_contribution_levels <- contribution_levels(
  x = state_corporate_taxes_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/state_corporate_taxes.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Social Benefits
federal_social_benefits_contribution_levels <- contribution_levels(
  x = federal_social_benefits_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_social_benefits.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# State Social Benefits
state_social_benefits_contribution_levels <- contribution_levels(
  x = state_social_benefits_test$data_series,
  mpc_matrix = readRDS("cache/mpc_matrices/state_social_benefits.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Rebate Checks
rebate_checks_contribution_levels <- contribution_levels(
  x = rebate_checks_test$data_series,
  mpc_matrix = readRDS("cache/mpc_matrices/rebate_checks.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Rebate Checks ARP
rebate_checks_arp_contribution_levels <- contribution_levels(
  x = rebate_checks_arp_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/rebate_checks_arp.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal UI
federal_ui_contribution_levels <- contribution_levels(
  x = federal_ui_test$data_series,  
  mpc_matrix = readRDS("cache/mpc_matrices/federal_ui.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# State UI
state_ui_contribution_levels <- contribution_levels(
  x = state_ui_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/state_ui.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)


# Federal Subsidies
federal_subsidies_contribution_levels <- contribution_levels(
  x = federal_subsidies_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_subsidies.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Aid to Small Businesses ARP
federal_aid_to_small_businesses_arp_contribution_levels <- contribution_levels(
  x = federal_aid_to_small_businesses_arp_test$data_series,  
  mpc_matrix = readRDS("cache/mpc_matrices/federal_aid_to_small_businesses_arp.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Other Direct Aid ARP
federal_other_direct_aid_arp_contribution_levels <- contribution_levels(
  x = federal_other_direct_aid_arp_test$data_series,  
  mpc_matrix = readRDS("cache/mpc_matrices/federal_other_direct_aid_arp.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Other Vulnerable ARP
federal_other_vulnerable_arp_contribution_levels <- contribution_levels(
  x = federal_other_vulnerable_arp_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_other_vulnerable_arp.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Student Loans
federal_student_loans_contribution_levels <- contribution_levels(
  x = federal_student_loans_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_student_loans.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# State Subsidies
state_subsidies_contribution_levels <- contribution_levels(
  x = state_subsidies_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/state_subsidies.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# Federal Health Outlays
federal_health_outlays_contribution_levels <- contribution_levels(
  x = federal_health_outlays_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/federal_health_outlays.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)

# State Health Outlays
state_health_outlays_contribution_levels <- contribution_levels(
  x = state_health_outlays_test$data_series, 
  mpc_matrix = readRDS("cache/mpc_matrices/state_health_outlays.rds"), 
  cumprod = cumprod_growth_consumption$cumprod
)


# Aggregate contribution levels by category
federal_levels <- 
  (federal_purchases_contribution_levels + 
     consumption_grants_contribution_levels + 
     investment_grants_contribution_levels) 

state_levels <- 
  (state_purchases_contribution_levels - 
     consumption_grants_contribution_levels - 
     investment_grants_contribution_levels)

taxes_levels <-
  (federal_non_corporate_taxes_contribution_levels + 
     state_non_corporate_taxes_contribution_levels + 
     federal_corporate_taxes_contribution_levels + 
     supply_side_ira_contribution_levels + 
     state_corporate_taxes_contribution_levels) 

transfers_levels <-
  (federal_social_benefits_contribution_levels + 
     state_social_benefits_contribution_levels + 
     rebate_checks_contribution_levels + 
     rebate_checks_arp_contribution_levels + 
     federal_ui_contribution_levels + 
     state_ui_contribution_levels + 
     federal_subsidies_contribution_levels + 
     federal_aid_to_small_businesses_arp_contribution_levels + 
     federal_other_direct_aid_arp_contribution_levels + 
     federal_other_vulnerable_arp_contribution_levels + 
     federal_student_loans_contribution_levels + 
     state_subsidies_contribution_levels + 
     federal_health_outlays_contribution_levels + 
     state_health_outlays_contribution_levels) 

consumption_levels <- (
  transfers_levels + taxes_levels
)

##################################
# DEFINE COUNTERFACTUAL FUNCTION #
##################################

# Define Real Level Function
# This function converts nominal levels into real 
real_level <- function(level, #the data in question 
                       deflator #the deflator for that data
                       ) 
  {
  result <- level / deflator
  return(result)
}

##############
# GET LEVELS #
##############

# Federal Purchases 
real_federal_levels <- real_level(federal_levels,
                                      federal_purchases_deflator)

# State Purchases
real_state_levels <- real_level(state_levels,
                                      state_purchases_deflator)

# Consumption
real_consumption_levels <- real_level(consumption_levels,
                                          consumption_deflator)

# Aggregate counterfactual levels
real_delta <- real_federal_levels + 
  real_state_levels + 
  real_consumption_levels

# Calculate Real GDP Counterfactual
real_gdp_counterfactual <- real_gdp - real_delta

percent_difference <- ( real_gdp / real_gdp_counterfactual - 1 ) * 100

# Output 
output <- data.frame(
  date, 
  real_federal_levels,
  real_state_levels,
  real_consumption_levels,
  real_delta,
  real_gdp,
  real_gdp_counterfactual
) %>%
  filter(date >= start_quarter - 1 & date <= end_quarter)

openxlsx::write.xlsx(output, file = glue('fim_levels.xlsx', overwrite = TRUE))
