---
title: "Tax forecast"
subtitle: "Alternative projections"
author: "Manuel Alcala Kovalski"
institute: "Hutchins Center"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r}
library('tidyverse')
library('fable')
library('tsibble')
library('broom')
tax_data <- readxl::read_xlsx('analysis/tax_data.xlsx') %>% 
  as_tibble()
```

---
```{r}
fit <- tax_data %>%  
  separate(date, into = c('year', 'quarter'), sep = ' - ') %>% 
  mutate(date = yearquarter(glue::glue('{year} {quarter}')), .before = everything()) %>% 
  as_tsibble(index = date) %>% 
  
  
  model(TSLM(corporate_income ~ corporate_profits)) 
  
augment(fit) %>% 
   ggplot(aes(x = date)) +
  geom_line(aes(y = corporate_income, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted")) 
```


---


---
```{r}
fit <- tax_data %>%  
  separate(date, into = c('year', 'quarter'), sep = ' - ') %>% 
  mutate(date = yearquarter(glue::glue('{year} {quarter}')), .before = everything()) %>% 
  as_tsibble(index = date) %>% 
  mutate(across(c(gdp, social_benefits),
                ~ q_g(.x),
                .names = '{.col}_growth')) %>% 
  
  
  model(TSLM(social_benefits_growth ~ trend())) 

  fit %>% 
augment(fit) %>% 
   ggplot(aes(x = date)) +
  geom_line(aes(y = social_benefits_growth, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted")) +
   labs(y = NULL,
    title = "Percentage change in social benefits"
  ) +
  scale_colour_manual(values=c(Data="black",Fitted="#D55E00")) +
  guides(colour = guide_legend(title = NULL))



fit <- forecast(fit)

fit %>% 
  autoplot(social_benefits_growth)
```

---